# Generated by Django 5.2.4 on 2025-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_order_billing_address_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('strawberry', 'Strawberry'), ('berry', 'Berry'), ('lemon', 'Lemon'), ('Organic Food', 'Organic Food'), ('Household Items', 'Household Items'), ('Reusable Products', 'Reusable Products'), ('Eco Personal Care', 'Eco Personal Care'), ('Green Gadgets', 'Green Gadgets'), ('other', 'Other')], max_length=20),
        ),
    ]
