# Generated by Django 5.2.4 on 2025-07-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_product_category'),
        ('app1', '0007_alter_product_category'),
    ]

    operations = [
    ]
