# Generated by Django 5.2.4 on 2025-07-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_merge_20250719_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Organic Food', 'Organic Food'), ('Household Items', 'Household Items'), ('Reusable Products', 'Reusable Products'), ('Eco Personal Care', 'Eco Personal Care'), ('Green Gadgets', 'Green Gadgets'), ('other', 'Other')], max_length=30),
        ),
    ]
