# Generated by Django 5.2.4 on 2025-07-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_billingaddress_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
